{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "order-placement.serviceAccountName" . }}
  labels:
    {{- include "order-placement.labels" . | nindent 4 }}
{{- end }}
