kafka:
  cluster: kafka
  replicationFactor: 2
  topics:
    - name: globex.tracking
      partitions: 1
      retention: -1
    - name: globex.orders
      partitions: 1
      retention: -1
argocd:
  enabled: true
  syncwave: "-2"

namespace: 