{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "globex-ui-v2-0.serviceAccountName" . }}
  labels:
    {{- include "globex-ui-v2-0.labels" . | nindent 4 }}
{{- end }}
