apiVersion: v2
name: globex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: inventory-app
    version: 0.1.0
    repository: file://inventory-app
  - name: catalog-app
    version: 0.1.0
    repository: file://catalog-app
  - name: order-placement
    version: 0.1.0
    repository: file://order-placement
  - name: activity-tracking-simulator
    version: 0.1.0
    repository: file://activity-tracking-simulator
  - name: globex-ui
    version: 0.1.0
    repository: file://globex-ui
  