apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recommendation-engine.name" . }}
  labels:
    {{- include "recommendation-engine.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    quarkus.kafka-streams.application-id={{ .Values.kafka.streams.applicationId }}

    quarkus.kafka-streams.topics={{ .Values.kafka.streams.topics }}

    quarkus.kafka-streams.commit.interval.ms={{ .Values.kafka.streams.commitIntervalMs }}

    kafka-streams.replication.factor={{ .Values.kafka.streams.replicationFactor }}

    
    mp.messaging.outgoing.kafka-streams.bootstrap.servers={{ include "kafka.bootstrap-server" . }}

    mp.messaging.connector.smallrye-kafka.security.protocol={{- include "kafka.security-protocol" . }}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{- include "kafka.sasl-mechanism" . }}

    {{- if eq (include "kafka.sasl-mechanism" .) "PLAIN" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="{{ include "kafka.client-id" . }}" \
        password="{{ include "kafka.client-secret" . }}";
    {{- end }}
    {{- if eq (include "kafka.sasl-mechanism" .) "SCRAM-SHA-512" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="{{ include "kafka.client-id" . }}" \
        password="{{ include "kafka.client-secret" . }}";
    {{- end }}

    tracking-event-topic=globex.tracking

