apiVersion: v1
kind: Service
metadata:
  name: {{ include "recommendation-engine.name" . }}
  labels:
    {{- include "recommendation-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.httpPortName }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "recommendation-engine.selectorLabels" . | nindent 4 }}
