apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb.name" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    {{- include "mongodb.argocd-syncwave" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mongodb.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "mongodb.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mongodb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - /etc/db/config/setup.sh > /tmp/replication.output &
          args:
            - '--replSet'
            - rs0
          env:
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongodb.initDb }}"
          ports:
            - name: mongodb
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data/configdb
              name: mongodb-configdb
            - mountPath: /data/db
              name: mongodb-db
            - mountPath: /etc/db/config
              name: config
      volumes:
        - name: mongodb-configdb
          persistentVolumeClaim:
            claimName: {{ include "mongodb.name" . }}-config
        - name: 'mongodb-db'
          persistentVolumeClaim:
            claimName: {{ include "mongodb.name" . }}-db
        - configMap:
            defaultMode: 493
            name: {{ include "mongodb.name" . }}
          name: config
