apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mongodb.name" . }}-config
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    {{- include "mongodb.argocd-syncwave" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.config.capacity }}

