---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: globex.tracking
  {{- if $.Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    strimzi.io/cluster: {{ include "kafka-broker.name" . }}
  annotations:
    {{- include "kafka-broker.argocd-syncwave" . | nindent 4 }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 1
    segment.bytes: 1073741824
  topicName: globex.tracking

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: globex.orders
  {{- if $.Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    strimzi.io/cluster: {{ include "kafka-broker.name" . }}    
  annotations:
    {{- include "kafka-broker.argocd-syncwave" . | nindent 4 }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 1
    segment.bytes: 1073741824
  topicName: globex.orders
