apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activity-tracking.name" . }}
  labels:
    {{- include "activity-tracking.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    mp.messaging.outgoing.tracking-event.topic={{ .Values.kafka.trackingEventTopic }}
    kafkaBootstrapServer: "{{ include "kafka.bootstrap-server" . }}"
    security.protocol={{- include "kafka.security-protocol" . }}
    sasl.mechanism={{- include "kafka.sasl-mechanism" . }}
    {{- if eq (include "kafka.sasl-mechanism" .) "PLAIN" }}
    sasl.jaas.config=sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="{{ include "kafka.client-id" . }}" \
        password="{{ include "kafka.client-secret" . }}";
    {{- end }}
    {{- if eq (include "kafka.sasl-mechanism" .) "SCRAM-SHA-512" }}
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="{{ include "kafka.client-id" . }}" \
        password="{{ include "kafka.client-secret" . }}";
    {{- end }}
