apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order-placement.name" . }}
  labels:
    {{- include "order-placement.labels" . | nindent 4 }}
    app.openshift.io/runtime: quarkus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "order-placement.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "order-placement.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "order-placement.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env: 
            - name: JSON_SCHEMA
              value: order-placement-payload.json
            - name: REGISTRY_URL
              value: '{{ .Values.serviceRegistry.url.api }}'
            - name: REGISTRY_GROUPID
              value: '{{ .Values.serviceRegistry.jsonSchema.groupId }}'
            - name: REGISTRY_ARTIFACTID
              value: '{{ .Values.serviceRegistry.jsonSchema.artifactId }}'
            - name: REGISTRY_ARTIFACTID_VERSION
              value: "1"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /deployments/config
              name: config
      volumes:
        - name: config
          secret:
            secretName: {{ include "order-placement.name" . }}
