apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-placement.name" . }}
  labels:
    {{- include "order-placement.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    mp.messaging.outgoing.order-event.bootstrap.servers={{ .Values.kafka.bootstrapServer }}
    mp.messaging.outgoing.order-event.topic={{ .Values.kafka.orderEventTopic }}

    mp.messaging.connector.smallrye-kafka.security.protocol={{- include "kafka.security-protocol" . }}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{- include "kafka.sasl-mechanism" . }}

    {{- if eq (include "kafka.sasl-mechanism" .) "PLAIN" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="{{ include "kafka.client-id" . }}" \
        password="{{ include "kafka.client-secret" . }}";
    {{- end }}
    {{- if eq (include "kafka.sasl-mechanism" .) "SCRAM-SHA-512" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
        username="{{ include "kafka.client-id" . }}" \
        password="{{ include "kafka.client-secret" . }}";
    {{- end }}