apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activity-tracking.name" . }}
  labels:
    {{- include "activity-tracking.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    mp.messaging.outgoing.tracking-event.topic={{ .Values.kafka.trackingEventTopic }}
