apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recommendation-engine.name" . }}
  labels:
    {{- include "recommendation-engine.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    quarkus.kafka-streams.application-id={{ .Values.kafka.streams.applicationId }}

    quarkus.kafka-streams.topics={{ .Values.kafka.streams.topics }}

    quarkus.kafka-streams.commit.interval.ms={{ .Values.kafka.streams.commitIntervalMs }}

    kafka-streams.replication.factor={{ .Values.kafka.streams.replicationFactor }}

    tracking-event-topic={{ .Values.kafka.topics.trackingEvent }}
